import { useEffect, useState } from "react";
import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { Download, Languages, Palette } from "lucide-react-native";
import { auth, firestore } from "../firebase";
import { useTheme, type ThemeMode } from "../theme/ThemeContext";
export function AdvancedPreferences() { const { theme, mode, setMode } = useTheme(); const [language, setLanguage] = useState("pt-BR"); useEffect(() => { AsyncStorage.getItem("app_language").then((value): void => { if (value) setLanguage(value); }).catch((): void => undefined); }, []); const changeLanguage = (value: string) => { setLanguage(value); AsyncStorage.setItem("app_language", value).catch((): void => undefined); };
  const backup = async () => { const uid = auth.currentUser?.uid; if (!uid) return; try { const [user, clientServices, providerServices] = await Promise.all([firestore.collection("Usuario").doc(uid).get(), firestore.collection("ServicosClientes").doc(uid).collection("ServicoStatus").get(), firestore.collection("ServicosAgendados").doc(uid).collection("ServicoStatus").get()]); const serialize = (value: any): any => value?.toDate ? value.toDate().toISOString() : Array.isArray(value) ? value.map(serialize) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, serialize(item)])) : value; const data = { version: 1, exportedAt: new Date().toISOString(), user: serialize(user.data()), clientServices: clientServices.docs.map((doc) => ({ id: doc.id, ...serialize(doc.data()) })), providerServices: providerServices.docs.map((doc) => ({ id: doc.id, ...serialize(doc.data()) })) }; const uri = `${FileSystem.cacheDirectory}backup-chamo-${Date.now()}.json`; await FileSystem.writeAsStringAsync(uri, JSON.stringify(data, null, 2)); await Sharing.shareAsync(uri, { mimeType: "application/json", dialogTitle: "Backup dos meus dados" }); } catch { Alert.alert("Backup", "Não foi possível exportar seus dados."); } };
  return <View style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}><View style={styles.titleRow}><Palette size={18} color="#FF8700" /><Text style={[styles.title, { color: theme.textPrimary }]}>Tema</Text></View><View style={styles.options}>{([['system','Automático'],['light','Claro'],['dark','Escuro']] as [ThemeMode,string][]).map(([value,label]) => <TouchableOpacity key={value} style={[styles.option, { borderColor: mode === value ? "#FF8700" : theme.border, backgroundColor: mode === value ? "#FFEDD5" : theme.actionBg }]} onPress={() => setMode(value)}><Text style={[styles.optionText, { color: mode === value ? "#E86F00" : theme.textSecondary }]}>{label}</Text></TouchableOpacity>)}</View><View style={styles.titleRow}><Languages size={18} color="#FF8700" /><Text style={[styles.title, { color: theme.textPrimary }]}>Idioma</Text></View><View style={styles.options}>{[["pt-BR","Português"],["en","English"],["es","Español"]].map(([value,label]) => <TouchableOpacity key={value} style={[styles.option, { borderColor: language === value ? "#FF8700" : theme.border }]} onPress={() => changeLanguage(value)}><Text style={[styles.optionText, { color: language === value ? "#E86F00" : theme.textSecondary }]}>{label}</Text></TouchableOpacity>)}</View><TouchableOpacity style={styles.backup} onPress={backup}><Download size={17} color="#FFFFFF" /><Text style={styles.backupText}>Exportar backup dos meus dados</Text></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 15, marginBottom: 16 }, titleRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 10 }, title: { fontSize: 14, fontWeight: "900" }, options: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 16 }, option: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 8 }, optionText: { fontSize: 10, fontWeight: "800" }, backup: { minHeight: 46, borderRadius: 13, backgroundColor: "#FF8700", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, backupText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" } });
