import { useEffect, useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { CalendarDays, CircleDollarSign, Star, Wrench } from "lucide-react-native";
import { auth, firestore } from "../firebase";
import { normalizeServiceStatus, ServiceStatus } from "../domain/service";
import { useTheme } from "../theme/ThemeContext";
export function ProviderDashboard() { const { theme } = useTheme(); const [services, setServices] = useState<any[]>([]); const [user, setUser] = useState<any>({}); useEffect(() => { const uid = auth.currentUser?.uid; if (!uid) return; const a = firestore.collection("ServicosAgendados").doc(uid).collection("ServicoStatus").onSnapshot((snapshot) => setServices(snapshot.docs.map((doc) => doc.data())), () => undefined); const b = firestore.collection("Usuario").doc(uid).onSnapshot((snapshot) => setUser(snapshot.data() || {}), () => undefined); return () => { a(); b(); }; }, []);
  const metrics = useMemo(() => { const now = new Date(); const startToday = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime(); const startWeek = startToday - ((now.getDay() + 6) % 7) * 86400000; const startMonth = new Date(now.getFullYear(), now.getMonth(), 1).getTime(); const completed = services.filter((item) => [ServiceStatus.CONCLUIDO, ServiceStatus.AVALIADO].includes(normalizeServiceStatus(item.status))); const earned = (from: number) => completed.filter((item) => (item.dataFinalizado?.toMillis?.() || item.dataAtualizacao?.toMillis?.() || 0) >= from).reduce((sum, item) => sum + Number(item.valor || 0), 0); const active = services.filter((item) => ![ServiceStatus.CONCLUIDO, ServiceStatus.AVALIADO, ServiceStatus.CANCELADO].includes(normalizeServiceStatus(item.status))).length; return { today: earned(startToday), week: earned(startWeek), month: earned(startMonth), active }; }, [services]);
  const cards = [{ label: "Hoje", value: `R$ ${metrics.today.toFixed(2)}`, icon: CircleDollarSign, color: "#16A34A" }, { label: "Semana", value: `R$ ${metrics.week.toFixed(2)}`, icon: CalendarDays, color: "#2563EB" }, { label: "Mês", value: `R$ ${metrics.month.toFixed(2)}`, icon: CircleDollarSign, color: "#7C3AED" }, { label: "Ativos", value: String(metrics.active), icon: Wrench, color: "#F59E0B" }, { label: "Avaliação", value: Number(user.avaliacao || 0).toFixed(1), icon: Star, color: "#F59E0B" }, { label: "Mensalidade", value: user.statusPagamento === "inadimplente" ? "Pendente" : "Em dia", icon: CalendarDays, color: user.statusPagamento === "inadimplente" ? "#DC2626" : "#16A34A" }];
  return <View style={styles.grid}>{cards.map(({ label, value, icon: Icon, color }) => <View key={label} style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}><Icon size={18} color={color} /><Text style={[styles.value, { color: theme.textPrimary }]} numberOfLines={1}>{value}</Text><Text style={[styles.label, { color: theme.textMuted }]}>{label}</Text></View>)}</View>;
}
const styles = StyleSheet.create({ grid: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginBottom: 18 }, card: { width: "31%", minHeight: 92, borderWidth: 1, borderRadius: 16, padding: 12 }, value: { fontSize: 14, fontWeight: "900", marginTop: 8 }, label: { fontSize: 10, fontWeight: "700", marginTop: 3 } });
