import { useState } from "react";
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ArrowLeft, Camera, Send, Trash2 } from "lucide-react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation, useRoute } from "@react-navigation/native";
import * as ImagePicker from "expo-image-picker";
import firebase from "firebase/compat/app";
import { auth, firestore } from "../firebase";
import { uploadFileUri } from "../utils/storageUpload";
import { useTheme } from "../theme/ThemeContext";

const categories = ["spam", "ofensa", "fraude", "assédio", "conteúdo impróprio"];
export default function Denunciar() {
  const navigation = useNavigation<any>(); const route = useRoute<any>(); const { theme } = useTheme();
  const { targetId, chatId, serviceId } = route.params || {}; const [category, setCategory] = useState("spam"); const [description, setDescription] = useState("");
  const [media, setMedia] = useState<{ uri: string; type: "image" | "video" }[]>([]); const [sending, setSending] = useState(false);
  const chooseMedia = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert("Permissão necessária", "Autorize o acesso para anexar evidências."); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images", "videos"], quality: 0.75, videoMaxDuration: 30 }); if (!result.canceled) { const asset = result.assets[0]; setMedia((current) => current.length >= 3 ? current : [...current, { uri: asset.uri, type: asset.type === "video" ? "video" : "image" }]); } };
  const submit = async () => { const uid = auth.currentUser?.uid; if (!uid || !targetId || description.trim().length < 10) return Alert.alert("Revise a denúncia", "Descreva o ocorrido com pelo menos 10 caracteres.");
    try { setSending(true); const ref = firestore.collection("Denuncias").doc(); const attachments = []; for (let index = 0; index < media.length; index += 1) { const item = media[index]; const extension = item.type === "video" ? "mp4" : "jpg"; const uploaded = await uploadFileUri(item.uri, `denuncias/${uid}/${ref.id}_${index}.${extension}`, item.type === "video" ? "video/mp4" : "image/jpeg"); attachments.push({ url: uploaded.url, type: item.type }); }
      const priority = category === "fraude" || category === "assédio" ? "alta" : "normal"; await ref.set({ reporterId: uid, targetId, chatId: chatId || null, serviceId: serviceId || null, category, priority, description: description.trim(), attachments, status: "pendente", history: [{ status: "pendente", actorId: uid, at: new Date() }], criadoEm: firebase.firestore.FieldValue.serverTimestamp(), atualizadoEm: firebase.firestore.FieldValue.serverTimestamp() }); Alert.alert("Denúncia enviada", "A equipe administrativa analisará as evidências.", [{ text: "OK", onPress: () => navigation.goBack() }]);
    } catch (error: any) { Alert.alert("Erro", error?.message || "Não foi possível enviar a denúncia."); } finally { setSending(false); } };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><View style={[styles.header, { borderBottomColor: theme.border }]}><TouchableOpacity onPress={() => navigation.goBack()}><ArrowLeft color={theme.textPrimary} /></TouchableOpacity><Text style={[styles.title, { color: theme.textPrimary }]}>Fazer denúncia</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content}><Text style={[styles.label, { color: theme.textPrimary }]}>Categoria</Text><View style={styles.chips}>{categories.map((item) => <TouchableOpacity key={item} style={[styles.chip, category === item && styles.chipActive]} onPress={() => setCategory(item)}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></TouchableOpacity>)}</View><Text style={[styles.label, { color: theme.textPrimary }]}>O que aconteceu?</Text><TextInput style={[styles.input, { color: theme.textPrimary, borderColor: theme.border, backgroundColor: theme.card }]} value={description} onChangeText={setDescription} multiline maxLength={2000} placeholder="Inclua detalhes que ajudem a equipe a analisar o caso..." placeholderTextColor={theme.textMuted} /><Text style={[styles.label, { color: theme.textPrimary }]}>Evidências ({media.length}/3)</Text><View style={styles.mediaRow}>{media.map((item, index) => <View key={`${item.uri}-${index}`} style={styles.preview}>{item.type === "image" ? <Image source={{ uri: item.uri }} style={styles.image} /> : <View style={styles.video}><Text style={styles.videoText}>Vídeo</Text></View>}<TouchableOpacity style={styles.remove} onPress={() => setMedia((current) => current.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={14} color="#FFFFFF" /></TouchableOpacity></View>)}{media.length < 3 && <TouchableOpacity style={[styles.add, { borderColor: theme.border }]} onPress={chooseMedia}><Camera color="#FF8700" /><Text style={styles.addText}>Anexar</Text></TouchableOpacity>}</View><TouchableOpacity style={[styles.submit, sending && { opacity: 0.6 }]} onPress={submit} disabled={sending}>{sending ? <ActivityIndicator color="#FFFFFF" /> : <Send size={18} color="#FFFFFF" />}<Text style={styles.submitText}>{sending ? "Enviando..." : "Enviar denúncia"}</Text></TouchableOpacity></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { padding: 16, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1 }, title: { fontSize: 19, fontWeight: "900" }, content: { padding: 18 }, label: { fontSize: 13, fontWeight: "900", marginTop: 14, marginBottom: 9 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { backgroundColor: "#E2E8F0", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999 }, chipActive: { backgroundColor: "#FF8700" }, chipText: { color: "#475569", fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, chipTextActive: { color: "#FFFFFF" }, input: { minHeight: 140, borderWidth: 1, borderRadius: 16, padding: 14, textAlignVertical: "top" }, mediaRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, preview: { width: 84, height: 84 }, image: { width: 84, height: 84, borderRadius: 12 }, video: { flex: 1, borderRadius: 12, backgroundColor: "#1E293B", alignItems: "center", justifyContent: "center" }, videoText: { color: "#FFFFFF", fontWeight: "800" }, remove: { position: "absolute", right: -5, top: -5, width: 25, height: 25, borderRadius: 13, backgroundColor: "#DC2626", alignItems: "center", justifyContent: "center" }, add: { width: 84, height: 84, borderRadius: 12, borderWidth: 1, borderStyle: "dashed", alignItems: "center", justifyContent: "center" }, addText: { color: "#FF8700", fontSize: 11, fontWeight: "800", marginTop: 5 }, submit: { minHeight: 52, borderRadius: 16, backgroundColor: "#DC2626", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, marginTop: 30 }, submitText: { color: "#FFFFFF", fontWeight: "900" } });
