import { useEffect, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { ArrowLeft, Download, ReceiptText } from "lucide-react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation } from "@react-navigation/native";
import { printToFileAsync } from "expo-print";
import { shareAsync } from "expo-sharing";
import { auth, firestore } from "../firebase";
import { useTheme } from "../theme/ThemeContext";

const date = (value: any) => value?.toDate?.().toLocaleDateString("pt-BR") || "—";
export default function FinanceiroPrestador() {
  const navigation = useNavigation<any>(); const { theme } = useTheme(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { const uid = auth.currentUser?.uid; if (!uid) { setLoading(false); return; } return firestore.collection("Usuario").doc(uid).collection("Mensalidades").orderBy("dueDate", "desc").onSnapshot((snapshot) => { setItems(snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }))); setLoading(false); }, () => setLoading(false)); }, []);
  const receipt = async (item: any) => { const user = await firestore.collection("Usuario").doc(auth.currentUser!.uid).get(); const html = `<html><body style="font-family:Arial;padding:40px"><h1>Recibo de mensalidade</h1><p>Recebemos de <b>${user.data()?.nome || "Prestador"}</b> o valor de <b>R$ ${Number(item.amount || 0).toFixed(2)}</b>.</p><p>Competência: ${item.periodKey || item.id}</p><p>Status: ${item.status}</p><p>Pagamento: ${date(item.paidAt)}</p><p>Identificador: ${item.mpPaymentId || item.id}</p><hr/><small>Documento gerado eletronicamente pelo aplicativo.</small></body></html>`; const file = await printToFileAsync({ html }); await shareAsync(file.uri, { mimeType: "application/pdf", dialogTitle: "Compartilhar recibo" }); };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><View style={[styles.header, { borderBottomColor: theme.border }]}><TouchableOpacity onPress={() => navigation.goBack()}><ArrowLeft color={theme.textPrimary} /></TouchableOpacity><Text style={[styles.title, { color: theme.textPrimary }]}>Histórico financeiro</Text><View style={{ width: 24 }} /></View>{loading ? <ActivityIndicator style={{ marginTop: 40 }} color="#FF8700" /> : <FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<View style={styles.empty}><ReceiptText size={42} color="#94A3B8" /><Text style={[styles.emptyText, { color: theme.textMuted }]}>Nenhuma fatura encontrada.</Text></View>} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}><View style={{ flex: 1 }}><Text style={[styles.period, { color: theme.textPrimary }]}>{item.periodKey || item.id}</Text><Text style={{ color: theme.textMuted }}>Vencimento: {date(item.dueDate)}</Text><Text style={[styles.amount, { color: theme.textPrimary }]}>R$ {Number(item.amount || 0).toFixed(2).replace(".", ",")}</Text><Text style={[styles.status, { color: item.status === "paid" ? "#15803D" : "#B45309" }]}>{item.status === "paid" ? "Pago" : "Pendente"}</Text></View>{item.status === "paid" && <TouchableOpacity style={styles.download} onPress={() => receipt(item)}><Download size={17} color="#FFFFFF" /><Text style={styles.downloadText}>Recibo</Text></TouchableOpacity>}</View>} />}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderBottomWidth: 1 }, title: { fontSize: 18, fontWeight: "900" }, list: { padding: 16, flexGrow: 1 }, card: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderRadius: 17, padding: 16, marginBottom: 10 }, period: { fontSize: 16, fontWeight: "900" }, amount: { fontSize: 18, fontWeight: "900", marginTop: 9 }, status: { fontSize: 11, fontWeight: "900", marginTop: 4 }, download: { backgroundColor: "#FF8700", borderRadius: 12, paddingHorizontal: 11, paddingVertical: 10, flexDirection: "row", gap: 6 }, downloadText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, empty: { flex: 1, alignItems: "center", justifyContent: "center" }, emptyText: { marginTop: 12 } });
