import { useEffect, useMemo, useState } from "react";
import { FlatList, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Download, Search } from "lucide-react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { auth, firestore } from "../firebase";
import { useTheme } from "../theme/ThemeContext";
import { ScreenHeader, StateView } from "../components/ui";
import { normalizeServiceStatus, serviceStatusLabel, ServiceStatus } from "../domain/service";
import { smartFilter } from "../utils/smartSearch";

const filters = ["todos", "ativos", "concluidos", "cancelados"] as const;
export default function HistoricoServicos() {
  const { theme } = useTheme(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<(typeof filters)[number]>("todos"); const [descending, setDescending] = useState(true);
  useEffect(() => { const uid = auth.currentUser?.uid; if (!uid) { setLoading(false); return; } return firestore.collection("ServicosClientes").doc(uid).collection("ServicoStatus").onSnapshot((snapshot) => { setItems(snapshot.docs.map((doc) => ({ id: doc.id, ...doc.data() }))); setLoading(false); }, () => setLoading(false)); }, []);
  const visible = useMemo(() => smartFilter(items, query, (item) => [item.estilo, item.tipo, item.nomePrestador, item.local, item.status]).filter((item) => { const status = normalizeServiceStatus(item.status); if (filter === "concluidos") return status === ServiceStatus.CONCLUIDO || status === ServiceStatus.AVALIADO; if (filter === "cancelados") return status === ServiceStatus.CANCELADO; if (filter === "ativos") return ![ServiceStatus.CONCLUIDO, ServiceStatus.AVALIADO, ServiceStatus.CANCELADO].includes(status); return true; }).sort((a, b) => { const aTime = a.dataAtualizacao?.toMillis?.() || a.criadoEm?.toMillis?.() || 0; const bTime = b.dataAtualizacao?.toMillis?.() || b.criadoEm?.toMillis?.() || 0; return descending ? bTime - aTime : aTime - bTime; }), [items, query, filter, descending]);
  const completed = items.filter((item) => [ServiceStatus.CONCLUIDO, ServiceStatus.AVALIADO].includes(normalizeServiceStatus(item.status))).length; const total = items.reduce((sum, item) => sum + Number(item.valorAceito ? item.valor : 0), 0);
  const exportCsv = async () => { const header = "servico,status,data,local,valor\n"; const rows = visible.map((item) => [item.estilo || item.tipo || "Serviço", serviceStatusLabel(item.status), item.data || "", item.local || "", Number(item.valor || 0).toFixed(2)].map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")).join("\n"); const uri = `${FileSystem.cacheDirectory}historico-servicos.csv`; await FileSystem.writeAsStringAsync(uri, `\ufeff${header}${rows}`, { encoding: FileSystem.EncodingType.UTF8 }); await Sharing.shareAsync(uri, { mimeType: "text/csv", dialogTitle: "Exportar histórico" }); };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><ScreenHeader title="Histórico" subtitle={`${items.length} serviços registrados`} /><View style={styles.content}><View style={styles.summary}><View style={[styles.kpi, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.kpiValue, { color: theme.textPrimary }]}>{completed}</Text><Text style={[styles.kpiLabel, { color: theme.textMuted }]}>Concluídos</Text></View><View style={[styles.kpi, { backgroundColor: theme.card, borderColor: theme.border }]}><Text style={[styles.kpiValue, { color: theme.textPrimary }]}>R$ {total.toFixed(2).replace(".", ",")}</Text><Text style={[styles.kpiLabel, { color: theme.textMuted }]}>Contratado</Text></View></View><View style={[styles.search, { backgroundColor: theme.card, borderColor: theme.border }]}><Search size={18} color={theme.textMuted} /><TextInput style={[styles.input, { color: theme.textPrimary }]} value={query} onChangeText={setQuery} placeholder="Serviço, profissional ou local" placeholderTextColor={theme.textMuted} /><TouchableOpacity onPress={exportCsv}><Download size={19} color="#2563EB" /></TouchableOpacity></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <TouchableOpacity key={item} style={[styles.chip, { borderColor: filter === item ? "#2563EB" : theme.border, backgroundColor: filter === item ? "#DBEAFE" : theme.card }]} onPress={() => setFilter(item)}><Text style={[styles.chipText, { color: filter === item ? "#1D4ED8" : theme.textSecondary }]}>{item}</Text></TouchableOpacity>)}<TouchableOpacity style={[styles.chip, { borderColor: theme.border, backgroundColor: theme.card }]} onPress={() => setDescending((value) => !value)}><Text style={[styles.chipText, { color: theme.textSecondary }]}>{descending ? "Mais recentes" : "Mais antigos"}</Text></TouchableOpacity></ScrollView></View>{loading ? <StateView kind="loading" /> : <FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListEmptyComponent={<StateView kind="empty" message="Nenhum serviço corresponde aos filtros." />} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: theme.card, borderColor: theme.border }]}><View style={{ flex: 1 }}><Text style={[styles.name, { color: theme.textPrimary }]}>{item.estilo || item.tipo || "Serviço"}</Text><Text style={[styles.meta, { color: theme.textMuted }]}>{item.nomePrestador || item.prestadorNome || "Profissional"} • {item.data || "Data não informada"}</Text><Text style={[styles.meta, { color: theme.textMuted }]}>{item.local || "Local não informado"}</Text></View><View><Text style={styles.status}>{serviceStatusLabel(item.status)}</Text><Text style={[styles.price, { color: theme.textPrimary }]}>R$ {Number(item.valor || 0).toFixed(2).replace(".", ",")}</Text></View></View>} />}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { padding: 16, paddingBottom: 0 }, summary: { flexDirection: "row", gap: 10 }, kpi: { flex: 1, borderWidth: 1, borderRadius: 16, padding: 14 }, kpiValue: { fontSize: 19, fontWeight: "900" }, kpiLabel: { fontSize: 11, fontWeight: "700", marginTop: 3 }, search: { minHeight: 48, borderWidth: 1, borderRadius: 15, paddingHorizontal: 12, flexDirection: "row", alignItems: "center", gap: 8, marginTop: 12 }, input: { flex: 1 }, filters: { gap: 7, paddingVertical: 11 }, chip: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 11, paddingVertical: 7 }, chipText: { fontSize: 10, fontWeight: "800", textTransform: "capitalize" }, list: { padding: 16, paddingTop: 4, flexGrow: 1 }, card: { borderWidth: 1, borderRadius: 17, padding: 15, marginBottom: 10, flexDirection: "row", gap: 10 }, name: { fontSize: 15, fontWeight: "900" }, meta: { fontSize: 11, marginTop: 4 }, status: { color: "#1D4ED8", fontSize: 10, fontWeight: "900", textAlign: "right" }, price: { fontSize: 13, fontWeight: "900", textAlign: "right", marginTop: 8 } });
