import { useState } from "react";
import { ActivityIndicator, Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { ArrowLeft, KeyRound, LogOut, MailCheck, ShieldCheck } from "lucide-react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useNavigation } from "@react-navigation/native";
import { auth, functions } from "../firebase";
import { useTheme } from "../theme/ThemeContext";
export default function SegurancaConta() {
  const navigation = useNavigation<any>(); const { theme } = useTheme(); const [loading, setLoading] = useState(""); const user = auth.currentUser;
  const run = async (key: string, action: () => Promise<unknown>, message: string) => { try { setLoading(key); await action(); Alert.alert("Segurança", message); } catch (error: any) { Alert.alert("Erro", error?.message || "A operação não foi concluída."); } finally { setLoading(""); } };
  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><View style={[styles.header, { borderBottomColor: theme.border }]}><TouchableOpacity onPress={() => navigation.goBack()}><ArrowLeft color={theme.textPrimary} /></TouchableOpacity><Text style={[styles.title, { color: theme.textPrimary }]}>Segurança da conta</Text><View style={{ width: 24 }} /></View><View style={styles.content}><View style={[styles.hero, { backgroundColor: theme.card, borderColor: theme.border }]}><ShieldCheck size={38} color="#2563EB" /><Text style={[styles.heroTitle, { color: theme.textPrimary }]}>{user?.emailVerified ? "E-mail verificado" : "Verificação pendente"}</Text><Text style={[styles.copy, { color: theme.textMuted }]}>{user?.email}</Text></View><Action icon={<MailCheck color="#2563EB" />} title="Verificar e-mail" subtitle="Envia um novo link de confirmação" theme={theme} loading={loading === "email"} onPress={() => run("email", () => user!.sendEmailVerification(), "Link de verificação enviado.")} /><Action icon={<KeyRound color="#F59E0B" />} title="Alterar senha" subtitle="Envia um link seguro para seu e-mail" theme={theme} loading={loading === "password"} onPress={() => run("password", () => auth.sendPasswordResetEmail(user!.email!), "Link para alterar a senha enviado.")} /><Action icon={<LogOut color="#DC2626" />} title="Encerrar outras sessões" subtitle="Revoga os acessos existentes em outros dispositivos" theme={theme} loading={loading === "sessions"} onPress={() => run("sessions", () => functions.httpsCallable("revokeMySessions")({}), "Sessões revogadas. Entre novamente nos seus dispositivos.")} /><View style={[styles.note, { borderColor: theme.border }]}><Text style={[styles.noteTitle, { color: theme.textPrimary }]}>Autenticação em duas etapas</Text><Text style={[styles.copy, { color: theme.textMuted }]}>A ativação por SMS depende do Firebase Identity Platform e de um provedor de telefone configurado.</Text></View></View></SafeAreaView>;
}
function Action({ icon, title, subtitle, theme, loading, onPress }: any) { return <TouchableOpacity style={[styles.action, { backgroundColor: theme.card, borderColor: theme.border }]} onPress={onPress} disabled={loading}>{icon}<View style={{ flex: 1 }}><Text style={[styles.actionTitle, { color: theme.textPrimary }]}>{title}</Text><Text style={[styles.copy, { color: theme.textMuted }]}>{subtitle}</Text></View>{loading && <ActivityIndicator color="#2563EB" />}</TouchableOpacity>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderBottomWidth: 1 }, title: { fontSize: 18, fontWeight: "900" }, content: { padding: 18 }, hero: { alignItems: "center", borderWidth: 1, borderRadius: 20, padding: 22, marginBottom: 14 }, heroTitle: { fontSize: 17, fontWeight: "900", marginTop: 10 }, copy: { fontSize: 12, lineHeight: 18, marginTop: 3 }, action: { flexDirection: "row", gap: 12, alignItems: "center", borderWidth: 1, borderRadius: 16, padding: 16, marginBottom: 10 }, actionTitle: { fontSize: 14, fontWeight: "900" }, note: { borderWidth: 1, borderRadius: 16, padding: 16, marginTop: 15 }, noteTitle: { fontSize: 14, fontWeight: "900" } });
